### PR TITLE
Type fixes

### LINKED ISSUE #37: Fix types for version 2.16.0
Some types were changed and new functions were added as part of 2.16.0. Types have not been updated yet for that version (needed to release early), so that needs to be done.

### PR DESCRIPTION
**Pull request by rohit-smpx**
- [x] Fix options not being optional in a lot of places
- [x] add template return types where possible
- [x] ~~#42 Added [`Readonly<>`](https://basarat.gitbooks.io/typescript/docs/types/readonly.html) to return types of cfg, cfg.get, cfg._getConfig so that atleast type errors are thrown on writing to objects~~
Moved to https://github.com/smartprix/cfg/issues/2
- [x] Update `Connect` options with new functions added `httpAuth`, `bearer`, `apiToken`, etc. Replace `request` `CookieJar` with `tough-cookie`  added in #36 
- [x] Closes #37 Various new options added to `RedisCache` constructor and methods
  - [x] `attachCache` option
  - [x] Pika option in redis config
  - [x] `useRedisCache` option
  - [x] Remove static functions as in 2a7212fd77113b553cd668582f2a8509f69c67dc

- [x] Also fixed `enqueue` function of DeQueue

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -755,7 +864,7 @@ declare module 'sm-utils' {
 		 * @param options object of {encoding}
 		 */
 		function sha256Hmac(string: string, options?: encodingOpts): string;
-
+
```
Comment (hit12369) [inline index.d.ts]: Trailing spaces.

Comment (rohit-smpx) [reply index.d.ts]: Done
